# Site settings
title:
email: james.smith9113@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Ph.D. candidate at the University of Colorado, Boulder in Prof. Sandeep Sharma's group. My research focuses on developing fast and accurate methods to calculate the electronic structure properties of challenging chemical species.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://jamesetsmith.github.io" # the base hostname & protocol for your site
github_username:  jamesETsmith
bitbucket_username: James_E_T_Smith
linkedin_username: james-smith-8525792b
researchgate_username: James_Smith158



# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
